name: fddp
description: >-
  Flutter CLI to auto-generate clean architecture feature folders with Provider,
  Bloc, Cubit, or Riverpod. One command builds your full data/domain/presentation structure.
version: 1.0.0
homepage: https://github.com/hamzaaitmansour/fddp
repository: https://github.com/hamzaaitmansour/fddp
issue_tracker: https://github.com/hamzaaitmansour/fddp/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.2
  mason_logger: ^0.3.2
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  fddp: fddp
